
# TURNOS

# DUPLO VINCULO (PROFESSOR 2X)
 # O PROFESSOR QUE APARECE 2X, ENTAO SUA JORNADA SERA MAIOR E ELE SERA TRATADO COMO DOIS PROFESSORES
 # SUA RESTRIÇÃO SERÁ TURNO QUANDO ESTIVER LOTADO

# LISTA DE CODIGOS DE LOTACAO DO PROFESSOR

# CH DIVERGENTESasas
